### ISSUE TITLE
Chap 0: Bugs ：conda换源遇报错'

### ISSUE THREAD

**Issue by w31r4** [datawhalechina/learn-python-the-smart-way-v2#13]
### 章节编号

chap 0 ，conda 换源

### 具体内容

win11 anaconda无法用notepad .condarc直接打开.condarc,而是需要使用conda config --set show_channel_urls yes，来生成该文件，并删除刚生成文件中的内容，才可以正常换源，否则会报错
![image](https://github.com/datawhalechina/learn-python-the-smart-way-v2/assets/114269655/6720c166-17ec-40cb-af9a-c28b741658dd)

### 错误描述

anaconda和miniconda还是不一样T--T，

**Comment by anine09** [comment]
你所描述的也是一种方案，但是我不觉得一定得使用这种方式才能生成 `.condarc` 文件，我需要详细的 notepad 报错信息才能判断是否需要修改文档内容。请详细描述下你在使用 `notepad .condarc` 的时候遇到了什么问题。

________________________________________
发件人: w31rd ***@***.***>
发送时间: 2023年7月20日 15:44
收件人: datawhalechina/learn-python-the-smart-way-v2
抄送: Epsilon Luoo; Assign
主题: [datawhalechina/learn-python-the-smart-way-v2] Chap 0 | Talks 0: Bugs ：conda换源遇报错' (Issue #13)

章节编号

chap 0 ，conda 换源

具体内容

win11 anaconda无法用notepad .condarc直接打开.condarc,而是需要使用conda config --set show_channel_urls yes，来生成该文件，并删除刚生成文件中的内容，才可以正常换源，否则会报错
[image]<https://user-images.githubusercontent.com/114269655/254810126-6720c166-17ec-40cb-af9a-c28b741658dd.png>

错误描述

anaconda和miniconda还是不一样T--T，

改进建议

No response

―

**Comment by w31r4** [comment]
我在notepad .condarc时并没有直接创建.condarc文件，而是系统进行了报错，创建并打开了一个无标题的txt文件

**Comment by w31r4** [comment]
.condarc默认是不会自动创建的，只有当用户第一次使用conda config命令时，系统才会自动创建.condarc文件。（有一个专用词，.condarc叫运行期配置文件）

**Comment by anine09** [comment]
是的，我调用 `notepad .condarc` 是在当前目录下使用记事本直接创建一个叫 .condarc 的文件，它类似于 vim .condarc，这无关运行时配置的事情

**Comment by w31r4** [comment]
但是只要创建过此文件就不会再报错了，刚才我把我的.condarc文件删除后再一次运行了note .condarc命令，这次并没有报错而是显示：
![image](https://github.com/datawhalechina/learn-python-the-smart-way-v2/assets/114269655/f5a36557-ef09-4ad3-b617-5ae0ab1ba3d5)
但我第一次创建此文件时，显示了报错

**Comment by w31r4** [comment]
我可能无法复现报错了，很抱歉

**Comment by anine09** [comment]
没有关系，我们最近会把 conda config --set show_channel_urls yes 这种方法给添加上去，感谢你对 P2S 项目的贡献。

**Comment by w31r4** [comment]
感谢你们无私提供的教程

**Comment by anine09** [comment]
该内容已经更新，将关闭本 issue
